# Cấu hình latexmk cho biên dịch tiếng Việt với XeLaTeX
$pdf_mode = 5; # 5 = xelatex
$xelatex = 'xelatex -synctex=1 -interaction=nonstopmode -file-line-error %O %S';
$biber = 'biber %O %S';
$clean_ext = 'bbl bcf run.xml synctex.gz fdb_latexmk fls';
